In [2]:
import sklearn.datasets
import numpy as np
import pandas as pd



In [3]:
bc=sklearn.datasets.load_breast_cancer()
print(bc)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [4]:
X=bc.data
print(X)


[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [5]:
Y=bc.target
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [6]:
print(X.shape)
print(Y.shape)

(569, 30)
(569,)


In [7]:
df=pd.DataFrame(bc.data,columns=bc.feature_names)
print(df.head())


   mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]


In [8]:
df["class"]=bc.target
print(df.head())

   mean radius  mean texture  ...  worst fractal dimension  class
0        17.99         10.38  ...                  0.11890      0
1        20.57         17.77  ...                  0.08902      0
2        19.69         21.25  ...                  0.08758      0
3        11.42         20.38  ...                  0.17300      0
4        20.29         14.34  ...                  0.07678      0

[5 rows x 31 columns]


In [9]:
print(df["class"].value_counts())

1    357
0    212
Name: class, dtype: int64


In [10]:
print(bc.target_names)

['malignant' 'benign']


In [11]:
X=df.drop("class",axis=1)
print(X.head())

   mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]


In [12]:
Y=df["class"]
print(Y.head())

0    0
1    0
2    0
3    0
4    0
Name: class, dtype: int64


In [13]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1) # test_size =0.1 is third argument which divides test data to 10% of original data

print(X_train.shape,X_test.shape)
print(X.shape)


(512, 30) (57, 30)
(569, 30)


In [14]:
print(Y_test,Y_train)
print(Y_test.shape,Y_train.shape)

334    1
301    1
48     1
193    0
428    1
100    0
438    1
295    1
240    1
328    0
387    1
557    1
538    1
185    1
42     0
441    0
373    0
362    1
553    1
242    1
84     1
136    1
116    1
178    1
198    0
462    1
498    0
277    0
94     0
389    0
561    1
482    1
253    0
93     1
513    1
122    0
415    1
337    0
257    0
511    1
507    1
497    1
111    1
475    1
256    0
208    1
279    1
69     1
519    1
32     0
539    1
413    1
310    1
264    0
493    1
293    1
241    1
Name: class, dtype: int64 190    0
47     0
216    1
490    1
168    0
      ..
207    0
144    1
239    0
346    1
527    1
Name: class, Length: 512, dtype: int64
(57,) (512,)


In [15]:
print(Y_test.value_counts())

1    39
0    18
Name: class, dtype: int64


Binarization
because MP neuron model works on 0/1 or low/high

In [16]:
x_binarised_3_train=X_train["mean radius"].map(lambda x:0 if x<15 else 1)

In [17]:

print(x_binarised_3_train.head(10))


190    0
47     0
216    0
490    0
168    1
142    0
500    1
514    1
89     0
224    0
Name: mean radius, dtype: int64


In [18]:
x_binarised_train=X_train.apply(pd.cut,bins=2,labels=[0,1])
x_binarised_test=X_test.apply(pd.cut,bins=2,labels=[0,1])

min value to median 0 is given
median to max value 1 is alloted

In [19]:
print(x_binarised_train.head(10))
print(x_binarised_test.head(10))

    mean radius mean texture  ... worst symmetry worst fractal dimension
190           0            0  ...              1                       1
47            0            0  ...              0                       0
216           0            0  ...              0                       0
490           0            0  ...              0                       0
168           0            1  ...              0                       0
142           0            0  ...              0                       0
500           0            0  ...              0                       0
514           0            0  ...              0                       0
89            0            0  ...              0                       0
224           0            0  ...              0                       0

[10 rows x 30 columns]
    mean radius mean texture  ... worst symmetry worst fractal dimension
334           0            0  ...              0                       0
301           0            

In [20]:
x_binarised_train=x_binarised_train.values
x_binarised_test=x_binarised_test.values

In [21]:
type(x_binarised_train)
type(x_binarised_test)

numpy.ndarray

MP Neurop model



In [32]:
import random
b=3
i=int(input("enter the  subject number"))
#i=random.randint(0,x_binarised_train.shape[])
if  np.sum(x_binarised_train[i])    >=b:
  print("output is 1 = malignant")
else:
  print("output is 0 =benign")  



enter the  subject number345
output is 1 = malignant


In [23]:
b=3
Y_pred=[]

for x in x_binarised_train:
  if np.sum(x,axis=0)>=b:
    Y_pred.append(1)
  else:
    Y_pred.append(0)
print(Y_pred)

z=list(Y_train)
print(z)

[1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 

In [24]:
correct_predctions=0
for a,b in zip(Y_pred,Y_train):
  if a==b:
    correct_predctions+=1

print("correct predictions=",correct_predctions)    

correct predictions= 72


In [25]:
accuracy=(correct_predctions/len(Y_train))*100
print(accuracy)
print(len(Y_train))

14.0625
512


3
